### ISSUE TITLE
Week 4 ready for review

### ISSUE THREAD

**Issue by cdmckinley** [cdmckinley/splatspot-interface-java#1]
@pawaitemadisoncollege week 4 is ready for review.

My biggest takeaway from this week is that I to take more time to learn the fundamental concepts properly. While being able to reference documentation is a good skill, it's not enough when I'm missing the foundation of this material.

"What challenged me?" Mostly myself, and my effort to finish the work quickly. I had several smaller issues too, such as thinking that Hibernate generated the IDs instead of MySQL, and going in a circle to fix something that I was the one who broke. I also made an assumption about the `runSQL` method. I thought it needed a slash, like the `PropertiesLoader` does.

I did use the debugger a bit to diagnose the part about the slash in the file name, it was helpful.

Putting each reference here would be quite a lot. They're in the journal from 9/28 to October 4th, which is 4 parts.

**Comment by pawaitemadisoncollege** [comment]
Hi @cdmckinley! From your reflection above and journal entries, it sounds like you worked through a lot of bumps and landed in on a more solid learning strategy for future work!  It looks like you have a good start with Hibernate and unit testing the dao.

As you continue adding functionality to your project:

- [ ] Verifying the entities are saved/updated/inserted correctly can be more thorough by implementing and using equals() on each entity - refer to the video Comparing Hibernate Entities with equals in week 5 for more detail.  An example of using the equals method in a unit test would be something like `assertTrue(expectedUser.equals(actualUser));`, which would be a good thing to verify after this assertion: https://github.com/cdmckinley/splatspot-interface-java/blob/fc354ca3f04f93160bcf907cdb01fd1e0a3b21c9/src/test/java/net/splatspot/persistence/UserDaoTest.java#L45
- [ ] I think the generic dao is already on your radar. I would recommend implementing the one-to-many relationship in the week 5 exercise and verifying everything works with unit tests _**before**_ adding in the generic dao.

**Comment by cdmckinley** [comment]
Thanks for the feedback. It's been implemented.
