### ISSUE TITLE
Checkpoint 3? (Deployment) and wrapping up the project

### ISSUE THREAD

**Issue by cdmckinley** [cdmckinley/splatspot-interface-java#10]
@pawaitemadisoncollege Checkpoint 3 is *finally* ready for review. The deployment can be found in the individual projects list in the student repository.

I wanted to get my refactoring done before deploying, and I took some extra time too. It should be ~99% in place now though!

The individual project has been quite a challenge, but I've also learned a lot over this course!

Having to switch project-direction was kind of a gamble, but I think it worked out well. This is what led to the refactoring, which was also a challenge that I overcame.

More of my key learning points/takeaways will be in my self-evaluation, if that's okay.

My resources are included in my journal, which is updated at least through the day of this issue's creation.

If all looks good with deployment, I can close #7

Then I still have my presentation and self-evaluation to finish. Should I also update any of my planning documents? The README has been updated, though I wonder about [my goals document](https://github.com/cdmckinley/splatspot-interface-java/blob/main/goals.md), which is very out of date, and potentially more relevant than [my user-stories](https://github.com/cdmckinley/splatspot-interface-java/blob/main/userStories.md). Should I update one or both of these?

And then if anything else jumps out that you think I should take care of, let me know.

**Comment by pawaitemadisoncollege** [comment]
Hi @cdmckinley!

It looks like you hit CP3! I can sign up, log in, and I see data on the jsp.  I was able to add a video. I did notice that if I tried to add a video id that does not exist, the application displayed a blank screen. I wonder if some validation can be added if the user adds a video id that does not actually exist? Thoughts?

Regarding updating your repository to reflect what was actually built: I think it makes sense to update the readme.md to reflect what the final product actually is. I don't think it's necessary to update planning documents as they were for planning purposes and we know that the actual product often varies from what was planned - that is ok.
