### ISSUE TITLE
Final Self-Evaluation Complete

### ISSUE THREAD

**Issue by cdmckinley** [cdmckinley/splatspot-interface-java#11]
@pawaitemadisoncollege my final self-evaluation is complete! If you have questions, feel free to let me know.

As a developer, the Java classes have taught me the most about patterns and the importance of objects, methods, and instance variable in programming. Each of these courses, especially Enterprise Java, helped me to think of code in new ways. I of course still have more to learn; at the same time, I feel ready to write more code that I can *put out there*, rather than keeping a private backup.

I believe I've earned an A or AB in this course. My reasoning is described and well-thought out in my [self-evaluation](https://github.com/cdmckinley/splatspot-interface-java/blob/main/self-eval.md)

**Comment by pawaitemadisoncollege** [comment]
Hi @cdmckinley - your adjustment to your learning process in this course really helped you achieve many of the competencies in this course. I agree with your assessment of having earned an "A".  It's been such a pleasure to work with you each week and I wish you the very best on the next part of your journey as a software developer. 

I will provide a review of your final indie project, but I wanted to confirm grades first as I realize there may be some anxiety related to waiting for those. :)
