### ISSUE TITLE
Lazy error trouble-shooting

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [cdmckinley/splatspot-interface-java#2]
Hi Craig, I am trying to reproduce the lazy initialization error that you referred to in Slack.  

A couple questions:

1. Was this happening when running the unit tests (versus the deployed app)?
2. Is the cleanup.sql file in GitHub correct? The version I see does not insert any records into shared_media, and I would expect some records to be on that table for unit testing purposes. https://github.com/cdmckinley/splatspot-interface-java/blob/08b694c31fe795bcced1cbc1fb88c9d9b9ee1e19/src/test/resources/cleanup.sql#L1-L4

**Comment by cdmckinley** [comment]
- I haven't tried the deployed app yet, only unit tests so far. I'll add updating the deployed app to my list for tomorrow.
- The `cleanup` script didn't have the data, though the insert test for `UserDao` (which does have data for SharedMedia) was what was failing when getting the retrieved data back from the database.
- The SQL files should be pretty up-to-date as of a few minutes ago. The test table won't start with the shared_media test data right now, but will get it through the `cleanup` script upon trying to test it

**Comment by cdmckinley** [comment]
I had redundant xml when I should have set it to use class annotations. The problem has been solved.

**Comment by pawaitemadisoncollege** [comment]
That's some great detective work @cdmckinley!
