### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by sandhyaa7** [cdmckinley/splatspot-interface-java#3]
@cdmckinley @pawaitemadisoncollege

  Design/Code Review 1

### Reviewer: Sandhya Sharma

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person|The problem statement accurately describes the purpose of the project. It does not have any slangs and are free of typos. It sounds professional. The problem with the application is explained and possible solution is presented on the problem statement clearly. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens |Navigation looked good, Craig mentioned he is working on adding couple navigation menu items. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>|The User class has 1-to-many annotation for sharedMediaList and vice versa. This relationship was also visible on database flow diagram. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverage.| The project structure looks good and .gitignore file has been implemented. The only redundant code I noticed is the code for session connection/close. Logging statements are used and property files are properly implemented. Craig mentioned, unit tests are still being worked on.|

**Comment by pawaitemadisoncollege** [comment]
Hi @sandhyaa7! Your review does a good job providing at least one "kudos" for each category. Are there any considerations for improvements that you can share?

**Comment by sandhyaa7** [comment]
I don't have any other suggestion.
