### ISSUE TITLE
Week 5 ready for review

### ISSUE THREAD

**Issue by cdmckinley** [cdmckinley/splatspot-interface-java#4]
@pawaitemadisoncollege week 5 should be complete.

The generic `Dao` class was my first generic class, so that was cool to learn! I also assume that I'll be making use of One to Many relationships more in the future.

This week, I felt more of the impact of not having used prior weeks' material as much as I should have. I got through, though it halted my progress for longer than I care to admit. I also had to re-think error handling, and making the generic `Dao` work for more what I needed it to took some research.

Resources used:

- Tutorialspoint [One to Many](https://www.tutorialspoint.com/hibernate/hibernate_one_to_many_mapping.htm) and [Many to One](https://www.tutorialspoint.com/hibernate/hibernate_many_to_one_mapping.htm)
- Hibernate Docs on JBoss
  - [OneToMany](https://docs.jboss.org/hibernate/jpa/2.1/api/javax/persistence/OneToMany.html) annotation
  - [SQLGrammarException](https://docs.jboss.org/hibernate/orm/3.2/api/org/hibernate/exception/SQLGrammarException.html). I know I used this but I forget what for.
  - [Path](https://docs.jboss.org/hibernate/jpa/2.2/api/javax/persistence/criteria/Path.html#get-java.lang.String-), mostly looking at `get` method
  - [Session](https://docs.jboss.org/hibernate/orm/5.2/javadocs/org/hibernate/Session.html)
- Realizing `FetchType.LAZY` was a bad idea
  - On StackOverflow: [This](https://stackoverflow.com/questions/22821695/how-to-fix-hibernate-lazyinitializationexception-failed-to-lazily-initialize-a) and [this](https://stackoverflow.com/questions/72181249/how-to-fix-org-hibernate-lazyinitializationexception-failed-to-lazily-initializ)
- [Not needing `*.hbm.xml` files if using annotations](https://stackoverflow.com/questions/25445627/if-we-are-using-annotation-based-hibernate-then-do-we-require-hbm-xml#:~:text=If%20you%27re%20referring%20to,to%20Hibernate%20XML%20Mapping%20files.)
- [Example annotations](https://mkyong.com/hibernate/hibernate-one-to-many-relationship-example-annotation/) and [JoinColumn documentation](https://docs.jboss.org/hibernate/jpa/2.1/api/javax/persistence/JoinColumn.html) to get the `user` property mapped to `user_id` in the database
- [JUnit assert](https://junit.org/junit4/javadoc/4.8/org/junit/Assert.html)
- Oracle JavaDocs
  - [Generic types](https://docs.oracle.com/javase/tutorial/java/generics/types.html)
  - [Class](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html) to get the simple name of a class (though I believe I've since removed the DAO class that used it)
  - [List](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/List.html)
- The course website, YouTube channel, and Slack

**Comment by pawaitemadisoncollege** [comment]
Hi @cdmckinley!  Your one-to-many and generic dao implementation are on target, and unit test cases (methods) are well-named to describe what they test.

A few things to keep in mind as you continue work:

- [ ] Javadoc. Yes, even on the test methods :) There is an IntelliJ plugin that can generate these for you (refer to the week 1 videos). It does a pretty good job when methods are well-named like yours are. You may need to tweak the comments a bit, but it'll do a lot of the work for you.

- [ ] Think about testing the delete scenarios in one-to-many relationships more fully. For example, if a user is deleted, what should happen to their shared media? What if a shared media record is deleted? Write tests to make sure whatever should happen, does happen. 

I suspect your project is ready for a checkpoint 2 review as well. I think the only thing needed at this point is an ERD.

**Comment by cdmckinley** [comment]
Thanks for the feedback!

I've added more JavaDocs to the tests, and added assertions for when related records should and should not be deleted. If you feel they're sufficient now, I'll close the issue.

I'll send you a Slack message about checkpoint 2 and the ERD

**Comment by pawaitemadisoncollege** [comment]
Hi @cdmckinley - those updates and additions take this to the next level.  Well done! You can close this up.
