### ISSUE TITLE
Checkpoint 2 ready for review

### ISSUE THREAD

**Issue by cdmckinley** [cdmckinley/splatspot-interface-java#5]
@pawaitemadisoncollege Checkpoint 2 is ready for review.

I have my database mostly designed and created, with the only things I'm aware of missing is a field linking Cognito, and a field on the `user` table for linking their Discord account. I plan to add the fields after I've made some more progress on my Professional Development Activity, and figured out what exactly I need for those two properties.

I have a generic `Dao` with create (insert), read (get), update, and delete.

I am not using `println` or `printStackTrace`.

I feel the big lesson during this time was to pay more attention to the course material, though learning the generic `Dao` was also cool (and fun), even if a bit challenging. I'm also glad I've learned some Test-Driven Development now.

My resources are in the journal.

Let me know if there are any questions

**Comment by pawaitemadisoncollege** [comment]
Hi @cdmckinley! Thanks for your Checkpoint 2 analysis.  Completing the weekly work in your indie project helped you hit this checkpoint sooner than later. 

**ERD**

- The field tying Cognito to your application should probably be whatever uniquely identifies them in cognito - often referred to as username. 
- Is there any need for a table related to this story: _I want to know when users are looking to play, so we can chat while we wait for others, or set our own rules._ Or will that be done entirely through the discord api?

**DAO**

- Generic Dao implemented
- Thoroughly unit-tested two entities with one-to-many relationship

**print statements**

-[ ] Could these be thrown so they can be logged within the implementing class instead? https://github.com/cdmckinley/splatspot-interface-java/blob/0bf2763c10f437e20ae0b9dcdd60de76121c577f/src/test/java/edu/matc/utilities/PropertiesLoader.java#L24-L28

**Other**

- Very good attention to journal and project plan. I hope you are finding this help you stay on track and reflect on what's going well and what could be better. Keep up the great work!

**Comment by cdmckinley** [comment]
@pawaitemadisoncollege Thanks for the feedback. I've had some thoughts and made some changes:

**ERD**
- Cognito username: I know I've had my share of username changes in the past. Would there either be a better 'Key' such as a unique ID from Cognito, or a way to update a username field on both my database and Cognito when someone wants to change it? (I may also be over-thinking this)
- My original plan wouldn't have needed to use a database to store players' statuses, but I wonder if your recommendation is a better practice.
  - My original thought was to get active users from the Discord side of things whenever someone accessed the page- Now that's starting to sound slow and process/network intensive though.
  - Would you agree that it's better to let the database hold those values, and have my web application subscribe to something on the Discord bot's end, to make database changes when those occur? Rather than checking each time users make requests? This would probably mean more activity over time, but less happening at once when many people use it concurrently

**print statements**
- I've made the change I believe you're describing. I've changed the `PropertiesLoader` to throw, and `Database` to catch and log

**Comment by pawaitemadisoncollege** [comment]
Hi @cdmckinley! 

I wasn't sure whether username in Cognito is changeable or not, so did a search for "cognito can I change username" which led me to this article: [https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-attributes.html). Check out the section called "User name and preferred user name".

Discord api versus Database - I wasn't necessarily trying to steer you one way or the other with my question; I was just looking to understand how that part will work.  The decision may be based on what the api provides, how performant it is, if there are any limits you need to be concerned with, etc.  Perhaps you can choose what you think is best based on what you discover related to that and test it out to confirm it meets your expectations.  Whichever option you choose does not have to be the final solution. There's always V2... V3... :)
