### ISSUE TITLE
Self-Evaluation

### ISSUE THREAD

**Issue by cdmckinley** [cdmckinley/splatspot-interface-java#6]
@pawaitemadisoncollege My in-progress self-evaluation is located [here](https://github.com/cdmckinley/splatspot-interface-java/blob/main/self-eval.md)

**Comment by pawaitemadisoncollege** [comment]
Hi @cdmckinley, I think your self eval is on target, if perhaps on the lower side in some cases. I'm going to list a few specific items for some of the categories that might help you think about and  identify some examples of your level of proficiency: 

**Industry Best Practices** in addition to the new tech such as hibernate and maven, this semester:
- small, single-purpose methods
- separation of concerns (database access is separate from the view, for example: no java code in the jsps, and no html in the java code). 
- DRY principle - Don't Repeat Yourself - no duplicate code. 

**Documentation**
- Are all of your classes and methods javadoc'd?

**Build and Deploy**
-  regularly deploying to aws 

**Producing Web Services**
- this is the week 9 exercise and the team project (depending on the approach your team takes)

**Auth**
- implementing cognito in your indie project will be key here.

**Git and GitHub**
- Team collaboration on a project using version control and branching. 

**Patterns**
- MVC too!

**Comment by cdmckinley** [comment]
@pawaitemadisoncollege alright if I make this the same issue? My self-evaluation has been updated for end of week 12 for time, though through week 13's work as I have that done. Let me know what you think.

**Comment by pawaitemadisoncollege** [comment]
Hi @cdmckinley! I think your updates accurately reflect your level of proficiency with the Ent Java key concepts. As you complete a final version of this over the next couple weeks, work to identify specific examples to add support to your levels. This can be done with a short blurb and perhaps links to some examples right in GitHub and/or a reference to how you helped somebody else with the concept in Slack. For each criteria, think: "What are one or two examples that clearly demonstrate how I hit the "meets expectations" mark?"

I've been impressed with your work this semester and you should be very proud of yourself - keep up that excellent effort!
